name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-pypi:
    strategy:
      matrix:
        distribution: [bdist_wheel, sdist]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install Node dependencies
        run: |
          pnpm i

      - name: Build Theme
        run: |
          pnpm build

      - name: Package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py ${{ matrix.distribution }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
