name: publish

on:
  push:
    tags:
    - '*'

jobs:
  publish-pypi:
    strategy:
      matrix:
        distribution: [bdist_wheel, sdist]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py ${{ matrix.distribution }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
